const missions=[
{title:"Senyals a la foscor",story:"Els sensors han detectat una transmissió molt feble. Necessitem aprendre a enviar un senyal abans de poder identificar-ne l'origen.",objective:"Programa dues Micro:bit perquè enviïn i rebin un senyal per ràdio.",steps:["Obriu MakeCode i creeu un projecte nou.","Configureu el mateix grup de ràdio a les dues Micro:bit.","Feu que una Micro:bit enviï un missatge quan premeu un botó.","Feu que l'altra mostri una icona quan rebi el missatge.","Repte final: detecteu el senyal secret enviat des de Nèbula."]},
{title:"Llum de supervivència",story:"La llum del planeta cau ràpidament. El vostre equip necessita un sistema que reaccioni a la foscor.",objective:"Creeu una llum automàtica utilitzant el sensor de llum de la Micro:bit.",steps:["Llegiu el nivell de llum.","Decidiu un valor a partir del qual considereu que és fosc.","Mostreu llum als LED quan el nivell sigui baix.","Proveu el programa tapant i destapant la Micro:bit."]},
{title:"Ruta del rover",story:"Un fragment del senyal prové d'una zona inaccessible. El Cutebot haurà d'arribar-hi sense xocar.",objective:"Programa el Cutebot perquè detecti i eviti obstacles.",steps:["Feu avançar el Cutebot.","Llegiu la distància amb el sensor d'ultrasons.","Quan trobi un obstacle, feu que s'aturi.","Feu-lo girar i continuar la ruta."]},
{title:"Coordenades finals",story:"Les tres pistes encaixen. Només falta executar la seqüència final per localitzar l'origen de la transmissió.",objective:"Combineu el que heu après i completeu el repte final de Nèbula.",steps:["Llegiu amb atenció la pista final del mestre.","Prepareu el programa abans de descarregar-lo.","Proveu-lo i corregiu els errors en equip.","Quan funcioni, demaneu la validació final."]}];
let state=JSON.parse(localStorage.getItem("nebula")||'{"team":"","done":0}'),current=0;
function save(){localStorage.setItem("nebula",JSON.stringify(state))}
function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");if(id==="map")renderMap()}
function start(){let t=document.getElementById("team").value.trim();if(!t)return;state.team=t;save();show("map")}
function renderMap(){document.getElementById("teamName").textContent=state.team;document.getElementById("progressText").textContent=state.done+" / "+missions.length;document.getElementById("bar").style.width=(state.done/missions.length*100)+"%";let box=document.getElementById("missions");box.innerHTML="";missions.forEach((m,i)=>{let d=document.createElement("div"),locked=i>state.done;d.className="node "+(locked?"locked ":"")+(i<state.done?"done":"");d.innerHTML="<b>MISSIÓ "+(i+1)+"</b><h3>"+m.title+"</h3><p>"+(i<state.done?"✓ Completada":locked?"Senyal bloquejat":"Senyal disponible")+"</p>";if(!locked)d.onclick=()=>openMission(i);box.appendChild(d)})}
function openMission(i){current=i;let m=missions[i];document.getElementById("missionNo").textContent="MISSIÓ "+(i+1)+" · "+String(i+1).padStart(2,"0");document.getElementById("missionTitle").textContent=m.title;document.getElementById("missionStory").textContent=m.story;document.getElementById("missionObjective").textContent=m.objective;document.getElementById("steps").innerHTML=m.steps.map(s=>'<div class="step">'+s+"</div>").join("");document.getElementById("code").value="";document.getElementById("error").textContent="";show("mission")}
function validateMission(){let entered=document.getElementById("code").value.trim();if(!entered){document.getElementById("error").textContent="Introduïu el codi que us donarà el mestre.";return}/* Codi provisional: substituir per validació segura al backend */if(entered!=="NEBULA"){document.getElementById("error").textContent="Codi incorrecte. Torneu-ho a provar.";return}if(current===state.done){state.done=Math.min(state.done+1,missions.length);save()}show("success")}
function continueMission(){show("map")}
function resetExpedition(){if(confirm("Voleu esborrar el progrés d'aquest equip?")){localStorage.removeItem("nebula");state={team:"",done:0};show("login")}}
if(state.team)show("map");